### ISSUE TITLE
support for rsrc_windows_arm64.syso

### ISSUE THREAD

**Issue by isaacwein** [tc-hib/go-winres#10]
does the `go-winres make` support arm64 Architect?
[processorArchitecture | Specifies the processor. Valid values include x86, amd64, arm and arm64. Optional.](https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#:~:text=of%20language%20to%20%22*%22.-,processorArchitecture,values%20include%20x86%2C%20amd64%2C%20arm%20and%20arm64.%20Optional.,-version)

**Comment by isaacwein** [comment]
the winres.json should have something like 
````json
 "processor-architecture": ["x86","amd64","arm","arm64"],
 ````

**Comment by tc-hib** [comment]
Hi,
This should work :

```shell
go-winres make --arch arm64
```

Feel free to file another issue if it doesn't.

Thanks

**Comment by isaacwein** [comment]
Thanks for adding
