### ISSUE TITLE
No resource image in exe after go build

### ISSUE THREAD

**Issue by brukin234** [tc-hib/go-winres#12]
Im doing all like in readme, but there is no resources. 
[Video](https://mega.nz/file/WXw3wYCY#Y3PIWjgkY4fxZ0fa-sRygXrDpso2Jt6RGXb9-s4QVXY) of what im doing
My go version is go1.20.4 windows/amd64

**Comment by gushmazuko** [comment]
Are you found a fix @brukin234 ?
