### ISSUE TITLE
How can I add a String Table in the winres.json file?

### ISSUE THREAD

**Issue by yg7001** [tc-hib/go-winres#13]
Would you like show me the format?

**Comment by yg7001** [comment]
I 've try below and many more format, but all not work!
"RT_STRING": {              
    "#1":{
      "0000":{          
          "ID": 1,
          "Caption":"my title"
       }        
    }          
  }

**Comment by tc-hib** [comment]
Hi,

I'm sorry, it's not possible.
Strings tables seem to be made of 2 types of resource : indexes and strings.

This tool only handles icons, cursors, version info and the manifest.
