### ISSUE TITLE
git-tag not working with simply

### ISSUE THREAD

**Issue by arojoal** [tc-hib/go-winres#2]
Hi,
I've just installed your tool with "go get github.com/tc-hib/go-winres@latest".
I'm trying to generate resources with "simply" command this way:

`go-winres simply --product-version=git-tag --file-version=git-tag --file-description="MKey process" --icon=winres/#1_0409.ico`

But when I compile de .exe file, It takes correctly the file description and ico but it shows "git-tag" texts as Product Version and "0.0.0.0" as File-Version.

If I generate the res file with `go-winres make --product-version=git-tag --file-version=git-tag` it works fine. What could I be doing wrong with the Simply command?

**Comment by tc-hib** [comment]
Hello,
Thanks a lot for reporting this bug.
This sounds like I forgot to call a function in the "simply" path, and I'll fix it as soon as possible.
Most likely tomorrow.
