### ISSUE TITLE
please add goreleaser support!

### ISSUE THREAD

**Issue by ericurse** [tc-hib/go-winres#4]

**Comment by tc-hib** [comment]
Hello, and thanks for your suggestion.
I would like to help, but I don't know what goreleaser is and what it means to support it.
Could you explain it to me?
Thanks.

**Comment by ericurse** [comment]
https://github.com/goreleaser/goreleaser

**Comment by tc-hib** [comment]
There's nothing to do on my part.
Use global hooks in goreleaser, or include your syso file in the repository.
